// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu5udOc7myJhObOiUr05y1xGAM5MlLPU0',
    appId: '1:710161743981:web:91f62f3486983de9ad3f64',
    messagingSenderId: '710161743981',
    projectId: 'silentvoice-96bf9',
    authDomain: 'silentvoice-96bf9.firebaseapp.com',
    storageBucket: 'silentvoice-96bf9.appspot.com',
    measurementId: 'G-98JBWXNHEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHAR0J974FIgsRLXrcBttIv7oVfB5Snrk',
    appId: '1:710161743981:android:f4b8076a091f674aad3f64',
    messagingSenderId: '710161743981',
    projectId: 'silentvoice-96bf9',
    storageBucket: 'silentvoice-96bf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiLAUf4RBGT1DpwruMqvDiyBpDvWqA8NE',
    appId: '1:710161743981:ios:4ac6ba5117f2eb9aad3f64',
    messagingSenderId: '710161743981',
    projectId: 'silentvoice-96bf9',
    storageBucket: 'silentvoice-96bf9.appspot.com',
    iosBundleId: 'com.example.deafDumbApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiLAUf4RBGT1DpwruMqvDiyBpDvWqA8NE',
    appId: '1:710161743981:ios:4ac6ba5117f2eb9aad3f64',
    messagingSenderId: '710161743981',
    projectId: 'silentvoice-96bf9',
    storageBucket: 'silentvoice-96bf9.appspot.com',
    iosBundleId: 'com.example.deafDumbApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu5udOc7myJhObOiUr05y1xGAM5MlLPU0',
    appId: '1:710161743981:web:601959c161c34733ad3f64',
    messagingSenderId: '710161743981',
    projectId: 'silentvoice-96bf9',
    authDomain: 'silentvoice-96bf9.firebaseapp.com',
    storageBucket: 'silentvoice-96bf9.appspot.com',
    measurementId: 'G-8N34VSCE5Y',
  );
}
